version: "3.5"

services:
  api:
    build:
      context: .
    restart: always
    command:
      [
        "sh",
        "-c",
        "pip install --upgrade pip && pip install debugpy -t /tmp && python /tmp/debugpy --listen 0.0.0.0:5680 -m uvicorn app.main.server:app --reload --host 0.0.0.0 --port 8080",
      ]
    volumes:
      - .:/usr/src/app
    ports:
      - 8080:8080
    env_file:
      - .env
